// node/node.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.0
// source: server/node.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreSegmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier for the segment.
	Nanoseed []byte `protobuf:"bytes,1,opt,name=nanoseed,proto3" json:"nanoseed,omitempty"`
	// The raw binary data of the segment.
	SegmentData   []byte `protobuf:"bytes,2,opt,name=segment_data,json=segmentData,proto3" json:"segment_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreSegmentRequest) Reset() {
	*x = StoreSegmentRequest{}
	mi := &file_server_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSegmentRequest) ProtoMessage() {}

func (x *StoreSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSegmentRequest.ProtoReflect.Descriptor instead.
func (*StoreSegmentRequest) Descriptor() ([]byte, []int) {
	return file_server_node_proto_rawDescGZIP(), []int{0}
}

func (x *StoreSegmentRequest) GetNanoseed() []byte {
	if x != nil {
		return x.Nanoseed
	}
	return nil
}

func (x *StoreSegmentRequest) GetSegmentData() []byte {
	if x != nil {
		return x.SegmentData
	}
	return nil
}

type StoreSegmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A confirmation message.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreSegmentResponse) Reset() {
	*x = StoreSegmentResponse{}
	mi := &file_server_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSegmentResponse) ProtoMessage() {}

func (x *StoreSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSegmentResponse.ProtoReflect.Descriptor instead.
func (*StoreSegmentResponse) Descriptor() ([]byte, []int) {
	return file_server_node_proto_rawDescGZIP(), []int{1}
}

func (x *StoreSegmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RetrieveSegmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier for the segment to retrieve.
	Nanoseed      []byte `protobuf:"bytes,1,opt,name=nanoseed,proto3" json:"nanoseed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveSegmentRequest) Reset() {
	*x = RetrieveSegmentRequest{}
	mi := &file_server_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveSegmentRequest) ProtoMessage() {}

func (x *RetrieveSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveSegmentRequest.ProtoReflect.Descriptor instead.
func (*RetrieveSegmentRequest) Descriptor() ([]byte, []int) {
	return file_server_node_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveSegmentRequest) GetNanoseed() []byte {
	if x != nil {
		return x.Nanoseed
	}
	return nil
}

type RetrieveSegmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw binary data of the requested segment.
	SegmentData   []byte `protobuf:"bytes,1,opt,name=segment_data,json=segmentData,proto3" json:"segment_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveSegmentResponse) Reset() {
	*x = RetrieveSegmentResponse{}
	mi := &file_server_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveSegmentResponse) ProtoMessage() {}

func (x *RetrieveSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveSegmentResponse.ProtoReflect.Descriptor instead.
func (*RetrieveSegmentResponse) Descriptor() ([]byte, []int) {
	return file_server_node_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveSegmentResponse) GetSegmentData() []byte {
	if x != nil {
		return x.SegmentData
	}
	return nil
}

var File_server_node_proto protoreflect.FileDescriptor

const file_server_node_proto_rawDesc = "" +
	"\n" +
	"\x11server/node.proto\x12\x04node\"T\n" +
	"\x13StoreSegmentRequest\x12\x1a\n" +
	"\bnanoseed\x18\x01 \x01(\fR\bnanoseed\x12!\n" +
	"\fsegment_data\x18\x02 \x01(\fR\vsegmentData\"0\n" +
	"\x14StoreSegmentResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"4\n" +
	"\x16RetrieveSegmentRequest\x12\x1a\n" +
	"\bnanoseed\x18\x01 \x01(\fR\bnanoseed\"<\n" +
	"\x17RetrieveSegmentResponse\x12!\n" +
	"\fsegment_data\x18\x01 \x01(\fR\vsegmentData2\xa4\x01\n" +
	"\vNodeService\x12E\n" +
	"\fStoreSegment\x12\x19.node.StoreSegmentRequest\x1a\x1a.node.StoreSegmentResponse\x12N\n" +
	"\x0fRetrieveSegment\x12\x1c.node.RetrieveSegmentRequest\x1a\x1d.node.RetrieveSegmentResponseB\x1aZ\x18imago-node/server;serverb\x06proto3"

var (
	file_server_node_proto_rawDescOnce sync.Once
	file_server_node_proto_rawDescData []byte
)

func file_server_node_proto_rawDescGZIP() []byte {
	file_server_node_proto_rawDescOnce.Do(func() {
		file_server_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_node_proto_rawDesc), len(file_server_node_proto_rawDesc)))
	})
	return file_server_node_proto_rawDescData
}

var file_server_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_server_node_proto_goTypes = []any{
	(*StoreSegmentRequest)(nil),     // 0: node.StoreSegmentRequest
	(*StoreSegmentResponse)(nil),    // 1: node.StoreSegmentResponse
	(*RetrieveSegmentRequest)(nil),  // 2: node.RetrieveSegmentRequest
	(*RetrieveSegmentResponse)(nil), // 3: node.RetrieveSegmentResponse
}
var file_server_node_proto_depIdxs = []int32{
	0, // 0: node.NodeService.StoreSegment:input_type -> node.StoreSegmentRequest
	2, // 1: node.NodeService.RetrieveSegment:input_type -> node.RetrieveSegmentRequest
	1, // 2: node.NodeService.StoreSegment:output_type -> node.StoreSegmentResponse
	3, // 3: node.NodeService.RetrieveSegment:output_type -> node.RetrieveSegmentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_node_proto_init() }
func file_server_node_proto_init() {
	if File_server_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_node_proto_rawDesc), len(file_server_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_node_proto_goTypes,
		DependencyIndexes: file_server_node_proto_depIdxs,
		MessageInfos:      file_server_node_proto_msgTypes,
	}.Build()
	File_server_node_proto = out.File
	file_server_node_proto_goTypes = nil
	file_server_node_proto_depIdxs = nil
}
