// node/node.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: server/node.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_StoreSegment_FullMethodName    = "/node.NodeService/StoreSegment"
	NodeService_RetrieveSegment_FullMethodName = "/node.NodeService/RetrieveSegment"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The gRPC service definition for a storage node.
type NodeServiceClient interface {
	// Stores a single segment (data or parity) on the node's filesystem.
	StoreSegment(ctx context.Context, in *StoreSegmentRequest, opts ...grpc.CallOption) (*StoreSegmentResponse, error)
	// Retrieves a single segment from the node's filesystem.
	RetrieveSegment(ctx context.Context, in *RetrieveSegmentRequest, opts ...grpc.CallOption) (*RetrieveSegmentResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) StoreSegment(ctx context.Context, in *StoreSegmentRequest, opts ...grpc.CallOption) (*StoreSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreSegmentResponse)
	err := c.cc.Invoke(ctx, NodeService_StoreSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RetrieveSegment(ctx context.Context, in *RetrieveSegmentRequest, opts ...grpc.CallOption) (*RetrieveSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveSegmentResponse)
	err := c.cc.Invoke(ctx, NodeService_RetrieveSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// The gRPC service definition for a storage node.
type NodeServiceServer interface {
	// Stores a single segment (data or parity) on the node's filesystem.
	StoreSegment(context.Context, *StoreSegmentRequest) (*StoreSegmentResponse, error)
	// Retrieves a single segment from the node's filesystem.
	RetrieveSegment(context.Context, *RetrieveSegmentRequest) (*RetrieveSegmentResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) StoreSegment(context.Context, *StoreSegmentRequest) (*StoreSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreSegment not implemented")
}
func (UnimplementedNodeServiceServer) RetrieveSegment(context.Context, *RetrieveSegmentRequest) (*RetrieveSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveSegment not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_StoreSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).StoreSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_StoreSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).StoreSegment(ctx, req.(*StoreSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RetrieveSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RetrieveSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RetrieveSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RetrieveSegment(ctx, req.(*RetrieveSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "node.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreSegment",
			Handler:    _NodeService_StoreSegment_Handler,
		},
		{
			MethodName: "RetrieveSegment",
			Handler:    _NodeService_RetrieveSegment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/node.proto",
}
