// root/root.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: chunker/root/root.proto

package root

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RootService_CreateImageChunks_FullMethodName = "/root.RootService/CreateImageChunks"
)

// RootServiceClient is the client API for RootService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The gRPC service definition for the root operations.
type RootServiceClient interface {
	// RPC method to process an image, segment it, and generate parity shards.
	CreateImageChunks(ctx context.Context, in *CreateImageChunksRequest, opts ...grpc.CallOption) (*ImageChunks, error)
}

type rootServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRootServiceClient(cc grpc.ClientConnInterface) RootServiceClient {
	return &rootServiceClient{cc}
}

func (c *rootServiceClient) CreateImageChunks(ctx context.Context, in *CreateImageChunksRequest, opts ...grpc.CallOption) (*ImageChunks, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageChunks)
	err := c.cc.Invoke(ctx, RootService_CreateImageChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RootServiceServer is the server API for RootService service.
// All implementations must embed UnimplementedRootServiceServer
// for forward compatibility.
//
// The gRPC service definition for the root operations.
type RootServiceServer interface {
	// RPC method to process an image, segment it, and generate parity shards.
	CreateImageChunks(context.Context, *CreateImageChunksRequest) (*ImageChunks, error)
	mustEmbedUnimplementedRootServiceServer()
}

// UnimplementedRootServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRootServiceServer struct{}

func (UnimplementedRootServiceServer) CreateImageChunks(context.Context, *CreateImageChunksRequest) (*ImageChunks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateImageChunks not implemented")
}
func (UnimplementedRootServiceServer) mustEmbedUnimplementedRootServiceServer() {}
func (UnimplementedRootServiceServer) testEmbeddedByValue()                     {}

// UnsafeRootServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RootServiceServer will
// result in compilation errors.
type UnsafeRootServiceServer interface {
	mustEmbedUnimplementedRootServiceServer()
}

func RegisterRootServiceServer(s grpc.ServiceRegistrar, srv RootServiceServer) {
	// If the following call pancis, it indicates UnimplementedRootServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RootService_ServiceDesc, srv)
}

func _RootService_CreateImageChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateImageChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootServiceServer).CreateImageChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RootService_CreateImageChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootServiceServer).CreateImageChunks(ctx, req.(*CreateImageChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RootService_ServiceDesc is the grpc.ServiceDesc for RootService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RootService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "root.RootService",
	HandlerType: (*RootServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateImageChunks",
			Handler:    _RootService_CreateImageChunks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chunker/root/root.proto",
}
